### PR TITLE
Create distinct API endpoints for views with match_param predicates

### LINKED ISSUE #21: Different views based on match_param predicates are not documented separately
When a route pattern includes placeholders that are used as predicates in a view's `match_param`, this means there can be multiple view functions with different documentation and unique URLs, however currently only one view's documentation is loaded and the path documented with APISpec includes placeholders the end user likely does not know about.

For example, the following route and views would currently only document as a single endpoint (`/foo/{id}/{view}`) when I think it should document two endpoints (`/foo/{id}/bar` and `/foo/{id}/baz`).

```python
config.add_route("foo", "/foo/{id}/{view}")

@view_config(route_name="foo", match_param="view=bar")
def foo_bar(request):
    """
    ---
    description: bar a foo
    """

@view_config(route_name="foo", match_param="view=baz")
def foo_baz(request):
    """
    ---
    description: baz a foo
    """
```

*Edit:* Grammar/clarity

### PR DESCRIPTION
**Pull request by smsearcy**
Replace match_param placeholders with predicate values so that the API doc shows the URLs that the end user would use.

Fixes #21

### CODE REVIEW

**Comment by smsearcy** [comment]
Do I need to "sign" `AUTHORS.md`?

**Comment by smsearcy** [comment]
I opened #23 to address failing tests.  The change to the Pyramid test harness will require updates to the test I wrote for this PR.

**Comment by marcin-lulek-cint** [comment]
@smsearcy Great stuff there! Yes you need to sign the authors :) Thank you for your awesome contributions.

**Comment by marcin-lulek-cint** [comment]
@smsearcy please sign on the PR with tests - I will merge that one first.

**Comment by smsearcy** [comment]
You're welcome, thank you for the useful library!

I added myself to AUTHORS in the #23 and then rebased this branch so that the new test works.

**Comment by ergo** [comment]
Thank you!

**Pull request merged**
